# Generated by Django 5.2.4 on 2025-08-06 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_rename_category_name_category_category_name'),
        ('store', '0002_items_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='category_table',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='category.category'),
        ),
    ]
