# Generated by Django 5.2.4 on 2025-08-13 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_items_category_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='items',
            options={'verbose_name': 'Item', 'verbose_name_plural': 'Items'},
        ),
        migrations.AddField(
            model_name='items',
            name='slug',
            field=models.SlugField(default='Test', max_length=100)
            ),
    ]
