# Generated by Django 5.2.4 on 2025-08-14 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_items_options_items_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='slug',
            field=models.SlugField(default='test', max_length=100),
        ),
    ]
