# Generated by Django 5.2.4 on 2025-08-14 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_items_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
