# Generated by Django 5.2.4 on 2025-08-21 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='items',
            new_name='Items',
        ),
    ]
