# Generated by Django 5.2.4 on 2025-09-11 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Phone_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
