# Generated by Django 5.2.4 on 2025-08-13 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_rename_category_name_category_category_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'categories'},
        ),
    ]
